In [2]:
import pandas as pd
from typing import Any
import requests
import pandas as pd
import matplotlib.pyplot as plt
from time import sleep
import os
from dotenv import load_dotenv
import psycopg
import seaborn as sns
import numpy as np
from sklearn.ensemble import RandomForestRegressor

In [ ]:
df=pd.read_pickle("ALL_10_YEARS")
columnas_enteras = [
    "altitud",
    "hrMedia",
    "hrMax",
    "hrMin",
    "dir" ,
    "horaPresMax",
    "horaPresMin" 
]
columnas_float =[
    "tmed",
    "prec",
    "tmin",
    "tmax",
    "pintMax",
    "velmedia",
    "racha",
    "presMax",
    "presMin",
    "sol"
]
columnas_hora=[
    "horatmin",
    "horatmax",
    "horaHrMax",
    "horaHrMin",
    "horaracha",
    
    "horaPIntMax"
]

columnas_horas_int=[
    "horaPresMax",
    "horaPresMin"
]



df["fecha"] = pd.to_datetime(df["fecha"],format="%Y-%m-%d")
df[columnas_enteras] = (df[columnas_enteras].apply(pd.to_numeric, errors="coerce").astype("Int64"))
df[columnas_float] = (df[columnas_float].apply(lambda columna: pd.to_numeric(columna.astype("string").str.strip().str.replace(",", ".", regex=False),errors="coerce")).astype("Float64"))

for columna in columnas_hora:
    df[f"{columna}_son_varias_h"] = (df[columna].eq("Varias"))
for columna in columnas_hora:
    df[columna] = (pd.to_datetime(df[columna].astype("string").str.strip(),format="%H:%M",errors="coerce").dt.strftime("%H:%M"))
    #.dt.strftime("%H:%M")
for columna in columnas_horas_int:
    df[columna] =df[columna].replace(24, 0).astype("Int64").astype("string") + ":00"
    df[columna] = (pd.to_datetime(df[columna].astype("string").str.strip(),format="%H:%M",errors="coerce").dt.strftime("%H:%M"))

df_limpio = df.astype(object).where(pd.notna(df), None)
df_limpio=df

In [79]:
import re

def normalizar_hora(valor):
    # Comprobamos si es nulo antes de convertir a string
    if pd.isna(valor):
        return np.nan
    valor = str(valor).strip()
    if valor in ("<NA>", "nan", "NaN", "None", ""):
        return np.nan
    if re.fullmatch(r"\d{1,2}", valor):
        return f"{int(valor):02d}:00"
    return valor

def convertir_datos_aemet(df):
    df = df.copy()

    # Fecha a datetime
    df["fecha"] = pd.to_datetime(df["fecha"], format="%Y-%m-%d", errors="coerce")

    # Categóricas / texto
    for col in ["indicativo", "provincia", "nombre"]:
        if col in df.columns:
            df[col] = df[col].astype("category")

    columnas_float = [
        "tmed", "prec", "tmin", "tmax", "hrMedia", "pintMax",
        "velmedia", "racha", "presMax", "presMin", "sol"
    ]

    columnas_hora = [
        "horatmin", "horatmax", "horaHrMax", "horaHrMin",
        "horaracha", "horaPresMax", "horaPresMin", "horaPIntMax"
    ]

    columnas_a_revisar = [c for c in columnas_float + columnas_hora if c in df.columns]

    # Detectar Acum / Varias / Ip
    mask_acum = pd.Series(False, index=df.index)
    mask_varias = pd.Series(False, index=df.index)
    mask_ip = pd.Series(False, index=df.index)

    for col in columnas_a_revisar:
        serie = df[col].apply(lambda x: str(x).strip().lower() if pd.notna(x) else np.nan)
        mask_acum |= (serie == "acum")
        mask_varias |= (serie == "varias")
        mask_ip |= (serie == "ip")

    df["precAcum"] = mask_acum.fillna(False)
    df["variasHoras"] = mask_varias.fillna(False)
    df["precIp"] = mask_ip.fillna(False)

    # Limpieza numérica
    def limpiar_numero(valor):
        if pd.isna(valor):
            return np.nan
        valor = str(valor).strip()
        if valor.lower() in ("ip",):
            return "0.05"
        if valor.lower() in ("acum", "varias", "<na>", "nan", "none", ""):
            return np.nan
        return valor.replace(",", ".")

    for col in columnas_float:
        if col in df.columns:
            df[col] = df[col].apply(limpiar_numero)
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # 4. Numéricos -> float
    for col in ["altitud", "hrMax", "hrMin", "dir"]:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce").astype(float)

    # 5. Columnas de hora -> normalizadas a HH:MM
    for col in columnas_hora:
        if col in df.columns:
            df[col] = df[col].apply(normalizar_hora)

    return df

# df_datos_limpio = convertir_datos_aemet(df_datos)

# pd.set_option('display.max_columns', None)
# df_datos_limpio.sample(50)

In [80]:
df=pd.read_pickle("ALL_10_YEARS")
df=convertir_datos_aemet(df)

In [81]:
WINDOW_SIZE: int = 20



temp = df[df["indicativo"] == "7250C"].sort_values(by="fecha")[[
    "fecha",
    "tmed",
    "hrMedia"#,
    # "dia_sin",
    # "dia_cos"
    ]].reset_index(drop=True)
temp["dia_sin"] = np.sin(2*np.pi*temp["fecha"].dt.dayofyear/365)
temp["dia_cos"] = np.cos(2*np.pi*temp["fecha"].dt.dayofyear/365)

train = temp.iloc[10:-365]
test = temp.iloc[-365:]

rows = []
for i in range(train.shape[0]-WINDOW_SIZE):
    date=temp.iloc[i+WINDOW_SIZE]["fecha"]
    hrMedia=temp.iloc[i+WINDOW_SIZE]["hrMedia"]
    day_sin = temp.iloc[i+WINDOW_SIZE]["dia_sin"]
    day_cos = temp.iloc[i+WINDOW_SIZE]["dia_cos"]  
    days=temp["tmed"].loc[i:WINDOW_SIZE+i].to_numpy()

    final_row = np.hstack([
        date,
        day_sin,
        day_cos,
        hrMedia,
        days
    ])

    rows.append(final_row)


df_estacion=pd.DataFrame(rows)
df_estacion.iloc[:, 4] = pd.to_numeric(df_estacion.iloc[:, 4], errors="coerce")
df_estacion=df_estacion.dropna()
df_estacion_X : pd.DataFrame = df_estacion.iloc[:, 1:-1]
df_estacion_Y : pd.DataFrame = df_estacion.iloc[:, -1]
corte=365
df_estacion_X_train : pd.DataFrame =df_estacion_X.iloc[:-corte]
df_estacion_X_test : pd.DataFrame=df_estacion_X.iloc[-corte:]
df_estacion_Y_train : pd.DataFrame=df_estacion_Y.iloc[:-corte]
df_estacion_Y_test : pd.DataFrame=df_estacion_Y.iloc[-corte:]

In [82]:
df_estacion

,0,1,2,3,4,5,6,7,8,9,...,15,16,17,18,19,20,21,22,23,24
0,2016-08-28,-0.845249,-0.534373,66.0,25.0,24.6,24.4,25.3,23.4,22.6,...,28.3,28.9,26.2,24.6,24.2,24.2,24.0,24.9,25.1,27.9
1,2016-08-29,-0.854322,-0.519744,70.0,24.6,24.4,25.3,23.4,22.6,24.5,...,28.9,26.2,24.6,24.2,24.2,24.0,24.9,25.1,27.9,26.8
2,2016-08-30,-0.863142,-0.504961,69.0,24.4,25.3,23.4,22.6,24.5,23.6,...,26.2,24.6,24.2,24.2,24.0,24.9,25.1,27.9,26.8,26.4
3,2016-08-31,-0.871706,-0.490029,69.0,25.3,23.4,22.6,24.5,23.6,26.1,...,24.6,24.2,24.2,24.0,24.9,25.1,27.9,26.8,26.4,25.0
4,2016-09-01,-0.880012,-0.474951,67.0,23.4,22.6,24.5,23.6,26.1,28.4,...,24.2,24.2,24.0,24.9,25.1,27.9,26.8,26.4,25.0,24.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3238,2025-07-10,-0.145799,-0.989314,67.0,28.0,28.0,28.8,27.4,27.6,27.4,...,29.0,28.6,28.3,28.2,27.8,28.6,28.3,29.4,28.2,27.6
3239,2025-07-11,-0.162807,-0.986658,68.0,28.0,28.8,27.4,27.6,27.4,29.6,...,28.6,28.3,28.2,27.8,28.6,28.3,29.4,28.2,27.6,27.8
3240,2025-07-12,-0.179767,-0.983709,44.0,28.8,27.4,27.6,27.4,29.6,27.5,...,28.3,28.2,27.8,28.6,28.3,29.4,28.2,27.6,27.8,29.1
3241,2025-07-13,-0.196673,-0.980469,57.0,27.4,27.6,27.4,29.6,27.5,28.3,...,28.2,27.8,28.6,28.3,29.4,28.2,27.6,27.8,29.1,27.4
3242,2025-07-14,-0.213521,-0.976938,56.0,27.6,27.4,29.6,27.5,28.3,29.5,...,27.8,28.6,28.3,29.4,28.2,27.6,27.8,29.1,27.4,28.1

In [83]:
df_estacion_X_train

,1,2,3,4,5,6,7,8,9,10,...,14,15,16,17,18,19,20,21,22,23
0,-0.845249,-0.534373,66.0,25.0,24.6,24.4,25.3,23.4,22.6,24.5,...,26.4,28.3,28.9,26.2,24.6,24.2,24.2,24.0,24.9,25.1
1,-0.854322,-0.519744,70.0,24.6,24.4,25.3,23.4,22.6,24.5,23.6,...,28.3,28.9,26.2,24.6,24.2,24.2,24.0,24.9,25.1,27.9
2,-0.863142,-0.504961,69.0,24.4,25.3,23.4,22.6,24.5,23.6,26.1,...,28.9,26.2,24.6,24.2,24.2,24.0,24.9,25.1,27.9,26.8
3,-0.871706,-0.490029,69.0,25.3,23.4,22.6,24.5,23.6,26.1,28.4,...,26.2,24.6,24.2,24.2,24.0,24.9,25.1,27.9,26.8,26.4
4,-0.880012,-0.474951,67.0,23.4,22.6,24.5,23.6,26.1,28.4,26.4,...,24.6,24.2,24.2,24.0,24.9,25.1,27.9,26.8,26.4,25.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2873,-0.162807,-0.986658,53.0,26.2,24.8,24.6,24.0,23.1,24.2,24.3,...,26.6,24.2,24.5,25.9,26.8,24.7,26.6,26.6,26.0,25.7
2874,-0.179767,-0.983709,60.0,24.8,24.6,24.0,23.1,24.2,24.3,26.0,...,24.2,24.5,25.9,26.8,24.7,26.6,26.6,26.0,25.7,29.0
2875,-0.196673,-0.980469,59.0,24.6,24.0,23.1,24.2,24.3,26.0,26.3,...,24.5,25.9,26.8,24.7,26.6,26.6,26.0,25.7,29.0,27.0
2876,-0.213521,-0.976938,67.0,24.0,23.1,24.2,24.3,26.0,26.3,27.0,...,25.9,26.8,24.7,26.6,26.6,26.0,25.7,29.0,27.0,29.2
2877,-0.230306,-0.973118,64.0,23.1,24.2,24.3,26.0,26.3,27.0,26.6,...,26.8,24.7,26.6,26.6,26.0,25.7,29.0,27.0,29.2,27.8

In [90]:
import xgboost as xgb
from sklearn.metrics import mean_absolute_error, mean_squared_error, root_mean_squared_error, r2_score

model: xgb.XGBRegressor = xgb.XGBRegressor(
    random_state=42,
    n_estimators=800,
    learning_rate=0.008
    )

model.fit(df_estacion_X_train, df_estacion_Y_train)
yhat: np.ndarray = model.predict(df_estacion_X_test)
print("MAE", mean_absolute_error(df_estacion_Y_test, yhat))
print("MSE", mean_squared_error(df_estacion_Y_test, yhat))
print("RMSE", root_mean_squared_error(df_estacion_Y_test, yhat))
print("R2", r2_score(df_estacion_Y_test, yhat))

MAE 1.2925420181065388
MSE 2.8925145232165885
RMSE 1.7007394048520745
R2 0.9268467164719186

In [24]:
modelo = RandomForestRegressor(
    n_estimators=1000,
    max_depth=10,
    random_state=42,
    min_samples_leaf=10,
    # criterion="poisson",
    bootstrap=True,
    n_jobs=-1
)

modelo.fit(df_estacion_X_train, df_estacion_Y_train)

RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                      n_jobs=-1, random_state=42)

In [25]:
pred = modelo.predict(estacion_1_X_test)
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

print("MAE :", mean_absolute_error(estacion_1_Y_test, pred))
print("RMSE:", np.sqrt(mean_squared_error(estacion_1_Y_test, pred)))
print("R²  :", r2_score(estacion_1_Y_test, pred))

MAE : 1.2898289119559625
RMSE: 1.7079333857785721
R²  : 0.926226543447013

In [52]:
def create_data_window(df:pd.DataFrame , date:str, indicativo:str, WINDOW :int = 10,) -> tuple[pd.DataFrame, float]:
    rows =[]
    df=df[df["indicativo"] == indicativo].sort_values(by="fecha")[["fecha","tmed","hrMedia","dia_sin","dia_cos"]].reset_index(drop=True)
    for i in range(train.shape[0]-WINDOW):
        dates=df.iloc[i+WINDOW]["fecha"]
        hrMedia=df.iloc[i+WINDOW]["hrMedia"]
        day_sin = df.iloc[i+WINDOW]["dia_sin"]
        day_cos = df.iloc[i+WINDOW]["dia_cos"]  
        days=df["tmed"].loc[i:WINDOW+i].to_numpy()

        final_row = np.hstack([
            dates,
            day_sin,
            day_cos,
            hrMedia,
            days
        ])
        rows.append(final_row)
        sdf=pd.DataFrame(rows)
        sdf = sdf[sdf.iloc[:, 0] == date]
        
    return (sdf.iloc[0, 1:-1], sdf.iloc[:, -1].iloc[0])

In [54]:
busca_b=create_data_window(df=df,date="2023-10-12",indicativo="7250C",WINDOW=20)
print(busca_b[0])
print(busca_b[1])

1    -0.981306
2     0.192452
3           73
4         23.2
5         21.2
6         21.5
7         21.2
8         23.0
9         23.0
10        22.6
11        22.9
12        23.4
13        24.2
14        23.0
15        23.0
16        23.8
17        22.8
18        22.6
19        21.6
20        22.4
21        21.5
22        21.9
23        22.1
Name: 2601, dtype: object
21.7

In [57]:
valor_a_predecir=create_data_window(
        df=df,
        date="2023-12-31",
        indicativo="0034X",
        WINDOW=20)
prediccion_from_modelos = modelos["0034X"].predict((valor_a_predecir[0].to_numpy().reshape(1, -1)))
print(prediccion_from_modelos[0])
print(valor_a_predecir[1])

9.258559740898306
8.2

In [37]:
modelos

{'0009X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0016A': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0016B': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0034X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0042Y': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0061X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0066X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0073X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0076': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0092X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0106X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0114X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0120X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0149D': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0149X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0158O': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0158X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0171X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0194D': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0200E': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0201D': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0201X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0222X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0244X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0252D': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0260X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0281Y': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0284X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0294B': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0312X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0320I': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0321': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0324A': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0341': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0341X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0349': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0360X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0363X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0367': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0370E': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0372C': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0385X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0394X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0411X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0413A': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0421E': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0421X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '0429X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1002Y': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1010X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1012P': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1014': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1014A': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1021X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1021Y': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1024E': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1025A': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1025X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1026X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1033X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1037X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1037Y': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1038X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1041A': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1044X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1048X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1049N': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1050J': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1052A': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1056K': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1057B': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1059X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1060X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1064L': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1069Y': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1074C': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1078C': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1078I': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1082': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1083B': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1083L': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1089U': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1096X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1109': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1109X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1111': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1111X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1124E': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1135C': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1152C': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1154H': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1159': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1167B': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1174I': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1176A': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1178Y': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1179B': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1183X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1186P': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1199X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1203D': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1207U': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1208H': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1210X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1212E': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1221D': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1223P': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1226X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1234P': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1249I': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1249X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1272B': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1276F': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1279X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1283U': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1297E': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1302F': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1309C': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1327A': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1331A': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1341B': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1342X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1344X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1347T': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1351': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1354C': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1363X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1387': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1387D': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1387E': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1390X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1393': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1399': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1400': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1406X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1410X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1428': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1435C': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1442U': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1446X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1465U': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1466A': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1468X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1473A': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),
 '1475X': RandomForestRegressor(max_depth=10, min_samples_leaf=10, n_estimators=1000,
                       n_jobs=-1, random_state=42),

In [28]:
df["indicativo"].nunique()

894

In [36]:
modelos = {}
estaciones_no_modelas=[]
cont=0
for indicativo, df_estacion in df.groupby("indicativo"):

    # df_estacion = df_estacion.dropna(subset=features + [target])

    WINDOW_SIZE: int = 20

    df_estacion["dia_sin"] = np.sin(2*np.pi*df_estacion["fecha"].dt.dayofyear/365)
    df_estacion["dia_cos"] = np.cos(2*np.pi*df_estacion["fecha"].dt.dayofyear/365)

    temp = df_estacion.sort_values(by="fecha")[[
        "fecha",
        "tmed",
        "hrMedia",
        "dia_sin",
        "dia_cos"
        ]].reset_index(drop=True)


    train = temp.iloc[10:-365]
    test = temp.iloc[-365:]

    rows = []
    for i in range(train.shape[0]-WINDOW_SIZE):
        date=temp.iloc[i+WINDOW_SIZE]["fecha"]
        hrMedia=temp.iloc[i+WINDOW_SIZE]["hrMedia"]
        day_sin = temp.iloc[i+WINDOW_SIZE]["dia_sin"]
        day_cos = temp.iloc[i+WINDOW_SIZE]["dia_cos"]  
        days=temp["tmed"].loc[i:WINDOW_SIZE+i].to_numpy()

        final_row = np.hstack([
            date,
            day_sin,
            day_cos,
            hrMedia,
            days
        ])

        rows.append(final_row)


    df_estacion=pd.DataFrame(rows)
    df_estacion=df_estacion.dropna()
    if len(df_estacion) < 1500:
        estaciones_no_modelas.append(indicativo)
        cont=1+cont
        print(f"La estación {indicativo} no tiene suficientes datos. Total de estaciones no modeladas {len(estaciones_no_modelas)}")
        continue

    df_estacion_X : pd.DataFrame = df_estacion.iloc[:, 1:-1]
    df_estacion_Y : pd.DataFrame = df_estacion.iloc[:, -1]
    corte=365
    df_estacion_X_train : pd.DataFrame =df_estacion_X.iloc[:-corte]
    df_estacion_X_test : pd.DataFrame=df_estacion_X.iloc[-corte:]
    df_estacion_Y_train : pd.DataFrame=df_estacion_Y.iloc[:-corte]
    df_estacion_Y_test : pd.DataFrame=df_estacion_Y.iloc[-corte:]

   

    X = df_estacion_X_train

    y = df_estacion_Y_train

    modelo = RandomForestRegressor(
        n_estimators=1000,
        max_depth=10,
        random_state=42,
        min_samples_leaf=10,
        # criterion="poisson",
        bootstrap=True,
        n_jobs=-1
    )

    modelo.fit(X, y)
    cont=1+cont
    print(f"Modelo de estación {indicativo} entrenado. Total: {cont} de {df["indicativo"].nunique()}. Total de estaciones no modeladas {len(estaciones_no_modelas)}")
    modelos[indicativo] = modelo

La estación 0002I no tiene suficientes datos. Total de estaciones 1
modelo de estación 0009X entrenado. Total: 2 de 894.
modelo de estación 0016A entrenado. Total: 3 de 894.
modelo de estación 0016B entrenado. Total: 4 de 894.
modelo de estación 0034X entrenado. Total: 5 de 894.
modelo de estación 0042Y entrenado. Total: 6 de 894.
modelo de estación 0061X entrenado. Total: 7 de 894.
modelo de estación 0066X entrenado. Total: 8 de 894.
modelo de estación 0073X entrenado. Total: 9 de 894.
modelo de estación 0076 entrenado. Total: 10 de 894.
modelo de estación 0092X entrenado. Total: 11 de 894.
modelo de estación 0106X entrenado. Total: 12 de 894.
modelo de estación 0114X entrenado. Total: 13 de 894.
modelo de estación 0120X entrenado. Total: 14 de 894.
modelo de estación 0149D entrenado. Total: 15 de 894.
modelo de estación 0149X entrenado. Total: 16 de 894.
modelo de estación 0158O entrenado. Total: 17 de 894.
modelo de estación 0158X entrenado. Total: 18 de 894.
modelo de estación 0171X entrenado. Total: 19 de 894.
modelo de estación 0194D entrenado. Total: 20 de 894.
modelo de estación 0200E entrenado. Total: 21 de 894.
modelo de estación 0201D entrenado. Total: 22 de 894.
modelo de estación 0201X entrenado. Total: 23 de 894.
modelo de estación 0222X entrenado. Total: 24 de 894.
modelo de estación 0244X entrenado. Total: 25 de 894.
modelo de estación 0252D entrenado. Total: 26 de 894.
La estación 0255B no tiene suficientes datos. Total de estaciones 2
modelo de estación 0260X entrenado. Total: 28 de 894.
modelo de estación 0281Y entrenado. Total: 29 de 894.
modelo de estación 0284X entrenado. Total: 30 de 894.
modelo de estación 0294B entrenado. Total: 31 de 894.
modelo de estación 0312X entrenado. Total: 32 de 894.
modelo de estación 0320I entrenado. Total: 33 de 894.
modelo de estación 0321 entrenado. Total: 34 de 894.
modelo de estación 0324A entrenado. Total: 35 de 894.
modelo de estación 0341 entrenado. Total: 36 de 894.
modelo de estación 0341X entrenado. Total: 37 de 894.
modelo de estación 0349 entrenado. Total: 38 de 894.
modelo de estación 0360X entrenado. Total: 39 de 894.
modelo de estación 0363X entrenado. Total: 40 de 894.
modelo de estación 0367 entrenado. Total: 41 de 894.
modelo de estación 0370E entrenado. Total: 42 de 894.
modelo de estación 0372C entrenado. Total: 43 de 894.
modelo de estación 0385X entrenado. Total: 44 de 894.
modelo de estación 0394X entrenado. Total: 45 de 894.
modelo de estación 0411X entrenado. Total: 46 de 894.
modelo de estación 0413A entrenado. Total: 47 de 894.
modelo de estación 0421E entrenado. Total: 48 de 894.
modelo de estación 0421X entrenado. Total: 49 de 894.
modelo de estación 0429X entrenado. Total: 50 de 894.
La estación 0433D no tiene suficientes datos. Total de estaciones 3
modelo de estación 1002Y entrenado. Total: 52 de 894.
modelo de estación 1010X entrenado. Total: 53 de 894.
modelo de estación 1012P entrenado. Total: 54 de 894.
modelo de estación 1014 entrenado. Total: 55 de 894.
modelo de estación 1014A entrenado. Total: 56 de 894.
modelo de estación 1021X entrenado. Total: 57 de 894.
modelo de estación 1021Y entrenado. Total: 58 de 894.
modelo de estación 1024E entrenado. Total: 59 de 894.
modelo de estación 1025A entrenado. Total: 60 de 894.
modelo de estación 1025X entrenado. Total: 61 de 894.
modelo de estación 1026X entrenado. Total: 62 de 894.
modelo de estación 1033X entrenado. Total: 63 de 894.
modelo de estación 1037X entrenado. Total: 64 de 894.
modelo de estación 1037Y entrenado. Total: 65 de 894.
modelo de estación 1038X entrenado. Total: 66 de 894.
modelo de estación 1041A entrenado. Total: 67 de 894.
modelo de estación 1044X entrenado. Total: 68 de 894.
modelo de estación 1048X entrenado. Total: 69 de 894.
modelo de estación 1049N entrenado. Total: 70 de 894.
modelo de estación 1050J entrenado. Total: 71 de 894.
modelo de estación 1052A entrenado. Total: 72 de 894.
La estación 1055B no tiene suficientes datos. Total de estaciones 4
modelo de estación 1056K entrenado. Total: 74 de 894.
modelo de estación 1057B entrenado. Total: 75 de 894.
modelo de estación 1059X entrenado. Total: 76 de 894.
modelo de estación 1060X entrenado. Total: 77 de 894.
modelo de estación 1064L entrenado. Total: 78 de 894.
modelo de estación 1069Y entrenado. Total: 79 de 894.
modelo de estación 1074C entrenado. Total: 80 de 894.
modelo de estación 1078C entrenado. Total: 81 de 894.
modelo de estación 1078I entrenado. Total: 82 de 894.
modelo de estación 1082 entrenado. Total: 83 de 894.
modelo de estación 1083B entrenado. Total: 84 de 894.
modelo de estación 1083L entrenado. Total: 85 de 894.
modelo de estación 1089U entrenado. Total: 86 de 894.
modelo de estación 1096X entrenado. Total: 87 de 894.
La estación 1103X no tiene suficientes datos. Total de estaciones 5
modelo de estación 1109 entrenado. Total: 89 de 894.
modelo de estación 1109X entrenado. Total: 90 de 894.
modelo de estación 1111 entrenado. Total: 91 de 894.
modelo de estación 1111X entrenado. Total: 92 de 894.
modelo de estación 1124E entrenado. Total: 93 de 894.
modelo de estación 1135C entrenado. Total: 94 de 894.
modelo de estación 1152C entrenado. Total: 95 de 894.
modelo de estación 1154H entrenado. Total: 96 de 894.
modelo de estación 1159 entrenado. Total: 97 de 894.
modelo de estación 1167B entrenado. Total: 98 de 894.
La estación 1167G no tiene suficientes datos. Total de estaciones 6
La estación 1167J no tiene suficientes datos. Total de estaciones 7
modelo de estación 1174I entrenado. Total: 101 de 894.
modelo de estación 1176A entrenado. Total: 102 de 894.
La estación 1178R no tiene suficientes datos. Total de estaciones 8
modelo de estación 1178Y entrenado. Total: 104 de 894.
modelo de estación 1179B entrenado. Total: 105 de 894.
modelo de estación 1183X entrenado. Total: 106 de 894.
modelo de estación 1186P entrenado. Total: 107 de 894.
modelo de estación 1199X entrenado. Total: 108 de 894.
modelo de estación 1203D entrenado. Total: 109 de 894.
modelo de estación 1207U entrenado. Total: 110 de 894.
modelo de estación 1208H entrenado. Total: 111 de 894.
modelo de estación 1210X entrenado. Total: 112 de 894.
modelo de estación 1212E entrenado. Total: 113 de 894.
modelo de estación 1221D entrenado. Total: 114 de 894.
modelo de estación 1223P entrenado. Total: 115 de 894.
modelo de estación 1226X entrenado. Total: 116 de 894.
modelo de estación 1234P entrenado. Total: 117 de 894.
modelo de estación 1249I entrenado. Total: 118 de 894.
modelo de estación 1249X entrenado. Total: 119 de 894.
modelo de estación 1272B entrenado. Total: 120 de 894.
modelo de estación 1276F entrenado. Total: 121 de 894.
modelo de estación 1279X entrenado. Total: 122 de 894.
modelo de estación 1283U entrenado. Total: 123 de 894.
modelo de estación 1297E entrenado. Total: 124 de 894.
modelo de estación 1302F entrenado. Total: 125 de 894.
modelo de estación 1309C entrenado. Total: 126 de 894.
modelo de estación 1327A entrenado. Total: 127 de 894.
modelo de estación 1331A entrenado. Total: 128 de 894.
modelo de estación 1341B entrenado. Total: 129 de 894.
modelo de estación 1342X entrenado. Total: 130 de 894.
modelo de estación 1344X entrenado. Total: 131 de 894.
modelo de estación 1347T entrenado. Total: 132 de 894.
modelo de estación 1351 entrenado. Total: 133 de 894.
modelo de estación 1354C entrenado. Total: 134 de 894.
modelo de estación 1363X entrenado. Total: 135 de 894.
modelo de estación 1387 entrenado. Total: 136 de 894.
modelo de estación 1387D entrenado. Total: 137 de 894.
modelo de estación 1387E entrenado. Total: 138 de 894.
modelo de estación 1390X entrenado. Total: 139 de 894.
modelo de estación 1393 entrenado. Total: 140 de 894.
modelo de estación 1399 entrenado. Total: 141 de 894.
modelo de estación 1400 entrenado. Total: 142 de 894.
modelo de estación 1406X entrenado. Total: 143 de 894.
modelo de estación 1410X entrenado. Total: 144 de 894.
modelo de estación 1428 entrenado. Total: 145 de 894.
modelo de estación 1435C entrenado. Total: 146 de 894.
La estación 1437O no tiene suficientes datos. Total de estaciones 9
modelo de estación 1442U entrenado. Total: 148 de 894.
modelo de estación 1446X entrenado. Total: 149 de 894.
La estación 1455I no tiene suficientes datos. Total de estaciones 10
modelo de estación 1465U entrenado. Total: 151 de 894.
modelo de estación 1466A entrenado. Total: 152 de 894.
modelo de estación 1468X entrenado. Total: 153 de 894.
modelo de estación 1473A entrenado. Total: 154 de 894.
modelo de estación 1475X entrenado. Total: 155 de 894.
modelo de estación 1476R entrenado. Total: 156 de 894.
modelo de estación 1477U entrenado. Total: 157 de 894.
modelo de estación 1477V entrenado. Total: 158 de 894.
modelo de estación 1484C entrenado. Total: 159 de 894.
La estación 1486E no tiene suficientes datos. Total de estaciones 11
modelo de estación 1489A entrenado. Total: 161 de 894.
modelo de estación 1495 entrenado. Total: 162 de 894.
modelo de estación 1496X entrenado. Total: 163 de 894.
modelo de estación 1505 entrenado. Total: 164 de 894.
modelo de estación 1518A entrenado. Total: 165 de 894.
modelo de estación 1521I entrenado. Total: 166 de 894.
modelo de estación 1521X entrenado. Total: 167 de 894.
modelo de estación 1541B entrenado. Total: 168 de 894.
modelo de estación 1542 entrenado. Total: 169 de 894.
modelo de estación 1549 entrenado. Total: 170 de 894.
modelo de estación 1561I entrenado. Total: 171 de 894.
modelo de estación 1583X entrenado. Total: 172 de 894.
modelo de estación 1631E entrenado. Total: 173 de 894.
modelo de estación 1639X entrenado. Total: 174 de 894.
modelo de estación 1658 entrenado. Total: 175 de 894.
modelo de estación 1679A entrenado. Total: 176 de 894.
modelo de estación 1690A entrenado. Total: 177 de 894.
modelo de estación 1696O entrenado. Total: 178 de 894.
modelo de estación 1700X entrenado. Total: 179 de 894.
modelo de estación 1701X entrenado. Total: 180 de 894.
modelo de estación 1706A entrenado. Total: 181 de 894.
modelo de estación 1719 entrenado. Total: 182 de 894.
modelo de estación 1723X entrenado. Total: 183 de 894.
modelo de estación 1730E entrenado. Total: 184 de 894.
modelo de estación 1735X entrenado. Total: 185 de 894.
modelo de estación 1738U entrenado. Total: 186 de 894.
modelo de estación 1740 entrenado. Total: 187 de 894.
modelo de estación 2005Y entrenado. Total: 188 de 894.
modelo de estación 2017Y entrenado. Total: 189 de 894.
modelo de estación 2030 entrenado. Total: 190 de 894.
modelo de estación 2044B entrenado. Total: 191 de 894.
modelo de estación 2048A entrenado. Total: 192 de 894.
modelo de estación 2059B entrenado. Total: 193 de 894.
modelo de estación 2084Y entrenado. Total: 194 de 894.
modelo de estación 2092 entrenado. Total: 195 de 894.
modelo de estación 2096B entrenado. Total: 196 de 894.
modelo de estación 2106B entrenado. Total: 197 de 894.
modelo de estación 2117D entrenado. Total: 198 de 894.
modelo de estación 2135A entrenado. Total: 199 de 894.
modelo de estación 2140A entrenado. Total: 200 de 894.
modelo de estación 2150H entrenado. Total: 201 de 894.
modelo de estación 2166Y entrenado. Total: 202 de 894.
modelo de estación 2172Y entrenado. Total: 203 de 894.
modelo de estación 2182C entrenado. Total: 204 de 894.
modelo de estación 2192C entrenado. Total: 205 de 894.
modelo de estación 2235U entrenado. Total: 206 de 894.
modelo de estación 2243A entrenado. Total: 207 de 894.
modelo de estación 2276B entrenado. Total: 208 de 894.
modelo de estación 2285B entrenado. Total: 209 de 894.
modelo de estación 2290Y entrenado. Total: 210 de 894.
modelo de estación 2296A entrenado. Total: 211 de 894.
modelo de estación 2298 entrenado. Total: 212 de 894.
modelo de estación 2302N entrenado. Total: 213 de 894.
modelo de estación 2311Y entrenado. Total: 214 de 894.
modelo de estación 2331 entrenado. Total: 215 de 894.
modelo de estación 2362C entrenado. Total: 216 de 894.
modelo de estación 2374X entrenado. Total: 217 de 894.
modelo de estación 2400E entrenado. Total: 218 de 894.
modelo de estación 2401X entrenado. Total: 219 de 894.
modelo de estación 2422 entrenado. Total: 220 de 894.
modelo de estación 2430Y entrenado. Total: 221 de 894.
modelo de estación 2444 entrenado. Total: 222 de 894.
modelo de estación 2453E entrenado. Total: 223 de 894.
modelo de estación 2456B entrenado. Total: 224 de 894.
modelo de estación 2462 entrenado. Total: 225 de 894.
modelo de estación 2465 entrenado. Total: 226 de 894.
modelo de estación 2471Y entrenado. Total: 227 de 894.
modelo de estación 2482B entrenado. Total: 228 de 894.
modelo de estación 2491C entrenado. Total: 229 de 894.
modelo de estación 2503B entrenado. Total: 230 de 894.
La estación 2503X no tiene suficientes datos. Total de estaciones 12
modelo de estación 2507Y entrenado. Total: 232 de 894.
modelo de estación 2512Y entrenado. Total: 233 de 894.
modelo de estación 2517A entrenado. Total: 234 de 894.
modelo de estación 2536D entrenado. Total: 235 de 894.
modelo de estación 2539 entrenado. Total: 236 de 894.
modelo de estación 2555B entrenado. Total: 237 de 894.
La estación 2565 no tiene suficientes datos. Total de estaciones 13
modelo de estación 2568D entrenado. Total: 239 de 894.
modelo de estación 2593D entrenado. Total: 240 de 894.
modelo de estación 2604B entrenado. Total: 241 de 894.
modelo de estación 2611D entrenado. Total: 242 de 894.
modelo de estación 2614 entrenado. Total: 243 de 894.
modelo de estación 2624C entrenado. Total: 244 de 894.
modelo de estación 2626Y entrenado. Total: 245 de 894.
modelo de estación 2630X entrenado. Total: 246 de 894.
modelo de estación 2661 entrenado. Total: 247 de 894.
La estación 2661B no tiene suficientes datos. Total de estaciones 14
modelo de estación 2664B entrenado. Total: 249 de 894.
modelo de estación 2701D entrenado. Total: 250 de 894.
modelo de estación 2728B entrenado. Total: 251 de 894.
modelo de estación 2734D entrenado. Total: 252 de 894.
modelo de estación 2737E entrenado. Total: 253 de 894.
modelo de estación 2742R entrenado. Total: 254 de 894.
modelo de estación 2755X entrenado. Total: 255 de 894.
modelo de estación 2766E entrenado. Total: 256 de 894.
modelo de estación 2775X entrenado. Total: 257 de 894.
modelo de estación 2777K entrenado. Total: 258 de 894.
modelo de estación 2789H entrenado. Total: 259 de 894.
modelo de estación 2804F entrenado. Total: 260 de 894.
La estación 2811A no tiene suficientes datos. Total de estaciones 15
modelo de estación 2828Y entrenado. Total: 262 de 894.
modelo de estación 2847X entrenado. Total: 263 de 894.
modelo de estación 2863C entrenado. Total: 264 de 894.
modelo de estación 2867 entrenado. Total: 265 de 894.
modelo de estación 2870 entrenado. Total: 266 de 894.
modelo de estación 2873X entrenado. Total: 267 de 894.
La estación 2882D no tiene suficientes datos. Total de estaciones 16
modelo de estación 2885K entrenado. Total: 269 de 894.
modelo de estación 2891A entrenado. Total: 270 de 894.
modelo de estación 2914C entrenado. Total: 271 de 894.
modelo de estación 2916A entrenado. Total: 272 de 894.
modelo de estación 2918Y entrenado. Total: 273 de 894.
modelo de estación 2926B entrenado. Total: 274 de 894.
modelo de estación 2930Y entrenado. Total: 275 de 894.
modelo de estación 2945A entrenado. Total: 276 de 894.
modelo de estación 2946X entrenado. Total: 277 de 894.
modelo de estación 2966D entrenado. Total: 278 de 894.
modelo de estación 2969U entrenado. Total: 279 de 894.
modelo de estación 2978X entrenado. Total: 280 de 894.
modelo de estación 3013 entrenado. Total: 281 de 894.
modelo de estación 3021Y entrenado. Total: 282 de 894.
La estación 3040Y no tiene suficientes datos. Total de estaciones 17
La estación 3044X no tiene suficientes datos. Total de estaciones 18
modelo de estación 3085Y entrenado. Total: 285 de 894.
modelo de estación 3094B entrenado. Total: 286 de 894.
modelo de estación 3099Y entrenado. Total: 287 de 894.
modelo de estación 3100B entrenado. Total: 288 de 894.
modelo de estación 3103 entrenado. Total: 289 de 894.
modelo de estación 3104Y entrenado. Total: 290 de 894.
modelo de estación 3110C entrenado. Total: 291 de 894.
modelo de estación 3111D entrenado. Total: 292 de 894.
modelo de estación 3125Y entrenado. Total: 293 de 894.
modelo de estación 3126Y entrenado. Total: 294 de 894.
modelo de estación 3129 entrenado. Total: 295 de 894.
modelo de estación 3130C entrenado. Total: 296 de 894.
modelo de estación 3140Y entrenado. Total: 297 de 894.
modelo de estación 3168D entrenado. Total: 298 de 894.
modelo de estación 3170Y entrenado. Total: 299 de 894.
modelo de estación 3175 entrenado. Total: 300 de 894.
modelo de estación 3182Y entrenado. Total: 301 de 894.
modelo de estación 3191E entrenado. Total: 302 de 894.
La estación 3194U no tiene suficientes datos. Total de estaciones 19
modelo de estación 3194Y entrenado. Total: 304 de 894.
modelo de estación 3195 entrenado. Total: 305 de 894.
modelo de estación 3196 entrenado. Total: 306 de 894.
modelo de estación 3200 entrenado. Total: 307 de 894.
modelo de estación 3209Y entrenado. Total: 308 de 894.
modelo de estación 3229Y entrenado. Total: 309 de 894.
modelo de estación 3245Y entrenado. Total: 310 de 894.
modelo de estación 3254Y entrenado. Total: 311 de 894.
modelo de estación 3260B entrenado. Total: 312 de 894.
modelo de estación 3266A entrenado. Total: 313 de 894.
modelo de estación 3268C entrenado. Total: 314 de 894.
La estación 3298X no tiene suficientes datos. Total de estaciones 20
modelo de estación 3305Y entrenado. Total: 316 de 894.
modelo de estación 3319D entrenado. Total: 317 de 894.
modelo de estación 3330Y entrenado. Total: 318 de 894.
modelo de estación 3337U entrenado. Total: 319 de 894.
modelo de estación 3338 entrenado. Total: 320 de 894.
modelo de estación 3343Y entrenado. Total: 321 de 894.
modelo de estación 3362Y entrenado. Total: 322 de 894.
modelo de estación 3365A entrenado. Total: 323 de 894.
modelo de estación 3386A entrenado. Total: 324 de 894.
modelo de estación 3391 entrenado. Total: 325 de 894.
modelo de estación 3422D entrenado. Total: 326 de 894.
modelo de estación 3423I entrenado. Total: 327 de 894.
modelo de estación 3427Y entrenado. Total: 328 de 894.
modelo de estación 3434X entrenado. Total: 329 de 894.
modelo de estación 3436D entrenado. Total: 330 de 894.
modelo de estación 3448X entrenado. Total: 331 de 894.
modelo de estación 3455X entrenado. Total: 332 de 894.
La estación 3463X no tiene suficientes datos. Total de estaciones 21
modelo de estación 3463Y entrenado. Total: 334 de 894.
modelo de estación 3469A entrenado. Total: 335 de 894.
modelo de estación 3475X entrenado. Total: 336 de 894.
modelo de estación 3494U entrenado. Total: 337 de 894.
modelo de estación 3503 entrenado. Total: 338 de 894.
modelo de estación 3504X entrenado. Total: 339 de 894.
modelo de estación 3512X entrenado. Total: 340 de 894.
modelo de estación 3514B entrenado. Total: 341 de 894.
modelo de estación 3516X entrenado. Total: 342 de 894.
modelo de estación 3519X entrenado. Total: 343 de 894.
modelo de estación 3526X entrenado. Total: 344 de 894.
modelo de estación 3531X entrenado. Total: 345 de 894.
modelo de estación 3536X entrenado. Total: 346 de 894.
modelo de estación 3540X entrenado. Total: 347 de 894.
modelo de estación 3547X entrenado. Total: 348 de 894.
modelo de estación 3562X entrenado. Total: 349 de 894.
modelo de estación 3565X entrenado. Total: 350 de 894.
modelo de estación 3576X entrenado. Total: 351 de 894.
modelo de estación 4007Y entrenado. Total: 352 de 894.
modelo de estación 4051Y entrenado. Total: 353 de 894.
modelo de estación 4061X entrenado. Total: 354 de 894.
modelo de estación 4064Y entrenado. Total: 355 de 894.
modelo de estación 4067 entrenado. Total: 356 de 894.
modelo de estación 4070Y entrenado. Total: 357 de 894.
modelo de estación 4075Y entrenado. Total: 358 de 894.
modelo de estación 4089A entrenado. Total: 359 de 894.
modelo de estación 4090Y entrenado. Total: 360 de 894.
modelo de estación 4091Y entrenado. Total: 361 de 894.